  # build an executable named simulator from my source code
  all: OS_Phase_1.c
		##gcc -pthread -Wall -o simulator OS_Phase_1.c
		## comment out the top line and uncomment this line to get the exact times, not using clock 
		gcc -pthread -Wall -o simulator correct_times_no_clock.c		

  clean:
		$(RM) OS_Phase_1