# build an executable named simulator from my source code
  all: OS_Phase_3.c
		gcc -pthread -Wall -o simulator OS_Phase_3.c
#########
#program that outputs clean times *for more info, read the README* :) 
  time:
		gcc -pthread -Wall -o floatTime correct_times_no_clock.c		
#########
  clean:
		$(RM) OS_Phase_3 time
