  # build an executable named simulator from my source code
  all: OS_Phase_2.c
		gcc -pthread -Wall -o simulator OS_Phase_2.c
#########
#comment out the above line and uncomment the line below this comment to get the exact times but as the program name implies it doesn't use sysetem clock *for more info, read the README* :) 
	
		#gcc -pthread -Wall -o simulator correct_times_no_clock.c		
#########
  clean:
		$(RM) OS_Phase_2
